############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Acerca de"
url = "about/"
weight = 2

[[main]]
name = "Porfolio"
url = "portfolio/"
weight = 3

[[main]]
name = "Contacto"
url = "#contact"
weight = 4
