############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Portfolio"
url = "portfolio/"
weight = 3

[[main]]
name = "Contact"
url = "#contact"
weight = 4

# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1
