############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Acerca de"
url = "about/"
weight = 2

[[main]]
name = "Porfolio"
url = "portfolio/"
weight = 3

[[main]]
weight = 4
name = "Dev-Pages"
hasChildren = true

[[main]]
parent = "Dev-Pages"
name = "Blog"
url = "blog/"

[[main]]
parent = "Dev-Pages"
name = "Contact"
url = "contact/"

[[main]]
parent = "Dev-Pages"
name = "Authors"
url = "authors/"

[[main]]
parent = "Dev-Pages"
name = "Categories"
url = "categories/"

# footer menu
[[footer]]
# name = "Acerca de"
# url = "about/"
# weight = 1
